'use client'

import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { usePathname, useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'zzzuh.com',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currPage = usePathname()

  let backgroundColor = "";

  if (currPage === "/") {
    backgroundColor = "bg-[#566165]"
  } else if (currPage === "/projects") {
    backgroundColor = "bg-[#E1E7C6]"
  } else if (currPage === "/contact") {
    backgroundColor = "bg-[#566165]"
  }

  return (
    <html lang="en" className={`${backgroundColor}`}>
      <Navbar></Navbar>
      <div className='w-full h-[500px]'>{children}</div>
    </html>
  )
}
